# config/packages/doctrine.yaml
doctrine:
  orm:
    mappings:
      User:
        is_bundle: false
        dir: '%kernel.project_dir%/src/User/Entity'
        prefix: 'App\User\Entity'
        alias: User
      