twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig"]
  globals:
    time_system_service: "@time_system_service"

when@test:
  twig:
    strict_variables: true
